### ISSUE TITLE
Cannot mix Markdown code within HTML struccture

### ISSUE THREAD

**Issue by Yikes2000** [ericleib/ngx-remark#3]
Cannot mix Markdown code within HTML structure.

Markdown code:
```
<div class="grid grid-cols-1">
  <div class="card">

**BOLD**

  </div>
</div>
```

Generated HTML code:
```
<div>
  <div class="grid grid-cols-1">
    <div class="card">
    </div>
  </div>
</div>

<p ng-reflect-node="[object Object]">
  <!--bindings={"ng-reflect-ng-switch-case": "paragraph"}-->
  ...
  <!--bindings={"ng-reflect-ng-switch-case": "html"}-->

  <strong ng-reflect-node="[object Object]">
    "BOLD"
  </strong>

  <!--ng-container--><!--bindings={"ng-reflect-ng-switch-case": "text"}-->
  ...
  <!--ng-container--><!--bindings={"ng-reflect-ng-for-track-by": "(index4, node2) => index4"}-->
  <!--container-->
</p>
```

Expected HTML code:
```
<div>
  <div class="grid grid-cols-1">
    <div class="card">

      <strong ...>
        "BOLD"
      </strong>

    </div>
  </div>
</div>
```

Side note: How to suppress the `<!-- . . . ->` HTML code?

**Comment by ericleib** [comment]
Thank you for reporting this. The reason this occurs is the markdown parser outputs a flat list of nodes:

- 1 html node with the opening elements: `<div class="grid grid-cols-1"><div class="card">`
- 1 paragraph node with the content ("BOLD")
- 1 html node with the closing elements: `</div>/div>`

So it's not hierarchical: It works if you render the html "as is" (expecting that opening tags will be closed later by closing tags). Unfortunately, we cannot do that with Angular templates.

This is how html nodes are currently rendered in the library:

```
<div *ngSwitchCase="'html'" [innerHTML]="child.value"></div>
```

So, the HTML is nested within a <div> and the browser does its best to fix the HTML if it is invalid (ie. close the opening tags).

If we wanted to handle this, I think the only way would be to transform the list of 3 nodes (html, paragraph, html) into 1 node (html), in which the paragraph has been rendered as HTML (with a library like rehype, but NOT using the template-based approach in this library). I guess this could be done with a unified plugin, but this seems too much of a edge case for this library.

Regarding the `<!-- . . . ->`: These are generated by Angular in dev mode. In prod build, Angular still generates comments, but they are empty: `<!--->`

**Comment by Yikes2000** [comment]
Thank you so much for the prompt explanation.  That makes sense.
